### ISSUE TITLE
not extending partition table

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/docker-storage-setup#106]
With `docker-1.8.2-10.el7.centos.x86_64` at least in AWS (`ami-3fb05d5f` in `us-west-2`), I'm not getting the partition table being resized after boot.  Will try to add some more debugging info here when I get a chance.

**Comment by rhvgoyal** [comment]
@cgwalters, Can you provide a link to the image please. Tried searching for above image in amazon, and can't find it. Would like to boot it and try.

**Comment by cgwalters** [comment]
You have to be in the right region - AMI IDs are region specific.  See https://wiki.centos.org/SpecialInterestGroup/Atomic/Download for the list, or switch to the `us-west-2` region which I was using.

**Comment by rhvgoyal** [comment]
Right, I changed the region and now I can see the image.

**Comment by rhvgoyal** [comment]
@cgwalters, I think we are not passing GROWPART=true in /etc/sysconfig/docker-storage-setup and that's why partitions backing root volume group is not being grown.

I see following in /etc/sysconfig/docker-storage-setup. I was expecting GROWPART=true for
cloud images.


-bash-4.2# cat /etc/sysconfig/docker-storage-setup 
# Edit this file to override any configuration options specified in
# /usr/lib/docker-storage-setup/docker-storage-setup.
#
# For more details refer to "man docker-storage-setup"

**Comment by cgwalters** [comment]
Closing in favor https://github.com/CentOS/sig-atomic-buildscripts/issues/59
