### ISSUE TITLE
root volume should auto-resize, but does not

### ISSUE THREAD

**Issue by jberkus** [projectatomic/docker-storage-setup#174]
OS: Fedora 25 Atomic Host
Platform: AWS, us-west-2

The Way It Is Now:  regardless of the size of the underlying EBS volume, the root volume (/dev/atomicos/root) is always 3GB.  Since that starts out 70% full, it only takes a tiny amount of user activity to cause the root volume to be 100% full and the system to error out.  This gives users an extremely negative impression of Atomic.

The Way It Should Be: the root volume should dynamically size, on cloud-init to 40% of the available disk space, with a minimum of 3GB, just like the docker volume.

It appears that this can happen if we ship with a different docker-storage-setup file by default.

**Comment by cgwalters** [comment]
https://pagure.io/fedora-atomic/issue/35

**Comment by rhvgoyal** [comment]
As of now docker-storage-setup does not grow pvs backing root volume group and rootfs by default. One needs to pass in following options to make it happen.

GROWPART=true
ROOT_SIZE=<size>

I always thought that cloud-init should take care of this and we should not be carrying this logic in docker-storage-setup. 

I guess only reason we are carrying it in docker-storage-setup because cloud-init can't deal with lvm? And instead of teaching cloud-init to deal with lvm, we wrote another script/service to be able to do what cloud-init should have done. Is that correct?

**Comment by cgwalters** [comment]
This bug isn't about growpart, it's about the 3G default, which is https://github.com/projectatomic/fedora-productimg-atomic

Let's move this ticket to https://pagure.io/fedora-atomic/issue/35
