### ISSUE TITLE
Do not create partition on devices

### ISSUE THREAD

**Issue by rhvgoyal** [projectatomic/docker-storage-setup#66]
I am wondering what's the need of creating partitions on devices passed in using DEVS=. Why not simply do pvcreate on these devices and add to volume group? This seems to unnnecessary increase the complexity of code and we have to use sfdisk. I think we should be able to drop it.

**Comment by rhvgoyal** [comment]
This creates another problem. If somebody specifies DEVS=vdb, we create partition /dev/vdb1 and add it to volume group. Now next time d-s-s runs it exits with error saying that vdb is a partitioned device. This is wrong. A user is not supposed to edit the /etc/sysconfig/docker-storage-setup again after pool has been created.

**Comment by eburgueno** [comment]
While I have nothing against using LVM on the raw device directly, the RHEL LVM Administration [guide](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Logical_Volume_Manager_Administration/LVM_components.html#multiple_partitions) does suggest creating a single partition spanning the entire disk, and then use that partition with LVM. I would say it would be best to keep things consistent.

> Red Hat recommends that you create a single partition that covers the whole disk to label as an LVM physical volume for the following reasons:
>- Administrative convenience
It is easier to keep track of the hardware in a system if each real disk only appears once. This becomes particularly true if a disk fails. In addition, multiple physical volumes on a single disk may cause a kernel warning about unknown partition types at boot.
>- Striping performance
LVM cannot tell that two physical volumes are on the same physical disk. If you create a striped logical volume when two physical volumes are on the same physical disk, the stripes could be on different partitions on the same disk. This would result in a decrease in performance rather than an increase.

**Comment by rhvgoyal** [comment]
I agree. For now I am closing it.
